### ISSUE TITLE
Mixpanel is breaking Flutter app for ios

### ISSUE THREAD

**Issue by viveky259259** [mixpanel/mixpanel-flutter#45] opened 2022-01-04 07:27 UTC
Whenever we turn off internet via Mobile data in iOS, Mixpanel is **crashing** application.

How to reproduce:
1. Implement Mixpanel flutter plugin
2. Run app in iPhone
3. Turn off  Wifi
4. Turn off mobile data

No stack trace found!

**Comment by zihejia** [comment] 2022-01-04 18:38
hi @viveky259259 , offline/no internal tracking is fully supported and it should NOT cause any crash. Are you sure this is from Mixpanel? Can you reproduce it in IDE on your mac with the internet off? I'm happy to reopen it if you can provide a crash log or more information to help us investigate further.

**Comment by zharfan104** [comment] 2022-01-06 04:21
Can you reopen this issues? We got this issue. The app itself is crashed in init.
Here is the log:
``` log
Crashed: com.apple.main-thread
0  mixpanel_flutter               0xc11c $s16mixpanel_flutter26SwiftMixpanelFlutterPluginC16handleInitialize33_786FF6545608A2FBFA64BEF2B35F6D58LL_6resultySo0E10MethodCallC_yypSgctF015$syXlSgIeyBy_ypU7Iegn_TRyXlSgIeyBy_Tf1ncn_nTf4nng_n + 1024
1  mixpanel_flutter               0x11740 $s16mixpanel_flutter26SwiftMixpanelFlutterPluginC6handle_6resultySo0E10MethodCallC_yypSgctF015$syXlSgIeyBy_ypM7Iegn_TRyXlSgIeyBy_Tf1ncn_nTf4nng_n + 440
2  mixpanel_flutter               0x8060 $s16mixpanel_flutter26SwiftMixpanelFlutterPluginC6handle_6resultySo0E10MethodCallC_yypSgctFTo + 76
3  Flutter                        0x324e44 (Missing)
4  Flutter                        0x37690 (Missing)
5  Flutter                        0x33e1a8 (Missing)
6  Flutter                        0x2d9f78 (Missing)
7  Flutter                        0x2dbdf8 (Missing)
8  CoreFoundation                 0xa48c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
9  CoreFoundation                 0xa44bc __CFRunLoopDoTimer + 1076
10 CoreFoundation                 0xa390c __CFRunLoopDoTimers + 328
11 CoreFoundation                 0x9d6c0 __CFRunLoopRun + 1944
12 CoreFoundation                 0x9c9f4 CFRunLoopRunSpecific + 600
13 GraphicsServices               0x3734 GSEventRunModal + 164
14 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
15 UIKitCore                      0xbcffcc UIApplicationMain + 168
16 Runner                         0x71f4 main + 6 (AppDelegate.swift:6)
17 libdyld.dylib                  0x1cf8 start + 4
```

**Comment by zihejia** [comment] 2022-01-06 05:11
No worries, could you share how you initialize Mixpanel?

**Comment by viveky259259** [comment] 2022-01-06 06:29
It is crashing in new version as well

**Comment by viveky259259** [comment] 2022-01-06 06:31
```
  static late Mixpanel mixpanel;
  Future<void> initMixpanel() async {
    mixpanel = await Mixpanel.init(
      "mixpanel_id",
      optOutTrackingDefault: false,
    );
    mixpanel.setLoggingEnabled(true);
  }
```

This is how I am initializing in flutter

**Comment by zharfan104** [comment] 2022-01-06 08:24
Before, when we crash the app, the code is look like this, the `Helper.loadToken()` is providing the token:

``` dart
    try {
      await Helper.loadToken()
          .then((token) async {
        _mixpanel = await Mixpanel.init(token);
      });
    } catch (_) {}
```

After we change the token to const, instead of fetching from firebase remote config, it not crash anymore

``` dart
  Future<void> initMixpanel() async {
    try {
      _mixpanel = await Mixpanel.init("const_token");
    } catch (_) {}
    return;
  }
```

We call the initMixpanel in our root widget `initState`.

**Comment by zihejia** [comment] 2022-01-06 23:33
Can anyone post a minimum sample app? I could not reproduce the crash. 
To @zharfan104 , which version are you using? You said it's not crash in simulator but crash in the device, can you reproduce it in debug mode in the device? Have you tried running iOS through Xcode? It will give you more information about the crash.

**Comment by zharfan104** [comment] 2022-01-07 05:05
I want to update, @zihejia

I found the bug, it also crash on debug mode in simulator (but only after I uninstall the app from simulator). 
It because the token value is `null`.

So, you can do this to make it not crash:
``` dart
   Future<void> initMixpanel() async {
    try {
      await Helper.loadToken()
          .then((token) async {
        _mixpanel = await Mixpanel.init(token);
      });
    } catch (_) {}
}
```

**Comment by viveky259259** [comment] 2022-01-11 08:18
Any update on this @zihejia ?

**Comment by viveky259259** [comment] 2022-01-11 08:39
@zihejia  updated app to 1.4.2 , still app is crashing

**Comment by zihejia** [comment] 2022-01-13 01:24
hi @viveky259259 , do you have a crash log?

**Comment by viveky259259** [comment] 2022-01-20 08:42
@zihejia Please find logs here


 flutter: ====ConnectivityResult.mobile=======
[        ] flutter: ====ConnectivityResult.mobile=======
[        ] flutter: ====ConnectivityResult.mobile=======
[        ] flutter: ====ConnectivityResult.mobile=======
[        ] flutter: AppLifecycleState.resumed

[ +468 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +7 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/C14FB6F5-7DFD-461E-9972-A3A3FEE080E6/tmp/iosappvvpQ5U/iosapp/)
[   +5 ms] process detach
[ +259 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[  +33 ms] "flutter run" took 2,20,882ms.
[ +279 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by zihejia** [comment] 2022-01-20 18:27
Hi @viveky259259 , it doesn't have any information related to Mixpanel. Is there any sample app or code snippet that you can share to reproduce this crash? Without these, it's really hard for us to help you out.

**Comment by viveky259259** [comment] 2022-02-01 10:39
Yes I know, but application is crashing when I add mixpanel to project

**Comment by zihejia** [comment] 2022-02-11 21:41
hi @viveky259259 , please try the latest version v1.4.5. It has several critical fixes for potential crashes for iOS. I'm closing this one now, please let me know if it needs to reopen.

**Closed by zihejia** 2022-02-11 21:41 UTC
