### ISSUE TITLE
iOS crash when called init with optOutTrackingDefault: true

### ISSUE THREAD

**Issue by kirill09** [mixpanel/mixpanel-flutter#11] opened 2021-04-14 12:27 UTC
When calling on iOS there is a crash. Library version 1.0.1
await Mixpanel.init('token', optOutTrackingDefault: true);

Assertion failed: You have to call initialize(token:) before calling the main instance, or define a new main instance if removing the main one: file Mixpanel/Mixpanel.swift, line 105

**Comment by zihejia** [comment] 2021-04-15 21:26
hi @kirill09 , could you share the full code snippet for initializing Mixpanel? Also, you could try the latest version 1.1.0

**Comment by killhead** [comment] 2021-04-16 10:57
my app is also crashing on 1.1.0 in release mode. Let's fix this.

**Comment by zihejia** [comment] 2021-04-16 17:10
hi @killhead , I have some trouble replicating the issue. Is it possible to attach a small sample app or a code snippet? Thank you!

**Comment by killhead** [comment] 2021-04-17 02:33
hi @zihejia 

```
Future<void> initMixpanel() async {
    mixpanel = await Mixpanel.init("project_token",optOutTrackingDefault: false);
  }
```

launched initState() of _MyAppState (MyApp is stateful widget):

```
@override
  void initState() {
    super.initState();
    initMixpanel();
  }
```

App launches into gray screen which means it's app crash. When I'm commenting out mixpanel_flutter from pubspec.yaml and removing further mixpanel commands, everything works just fine. So, it's definitely mixpanel library that creates the issue.

Important: issue is visible only when running app in release mode. Easiest way to do that is: flutter run --release

Launched my app via flutter run --release --verbose and attaching output here, but not sure if any issue can be seen within the output.

Mixpanel SDK version is 1.1.0

Here is flutter doctor -v output for reference:

```
[mixpanel.log](https://github.com/mixpanel/mixpanel-flutter/files/6328503/mixpanel.log)
```

**Comment by killhead** [comment] 2021-04-17 03:02
@zihejia in addition to info above, I tried adding print("App started"); into Widget build(BuildContext context)

as my console output is empty, I think it's either mixpanelInit() which is silently crashing or package initialization in release mode.

So, steps to reproduce is:
1. switch to stable channel: flutter channel stable
2. build into release mode: flutter run --release

I hope this helps.

**Comment by zihejia** [comment] 2021-04-17 18:39
hi @killhead , your problem is different than @kirill09 cause the `Assertion` crash will never happen in the release build, only in the debug mode. I used the same env as yours and also tried `--release` but still had no luck replicating the issue. The attached `mixpanel.log` does not show any errors. 

For both @kirill09 and @killhead, Could you try running the iOS project(under ios/Runner.xcworkspace) by using Xcode? Also you can turn on the Mixpanel log([setLoggingEnabled](https://mixpanel.github.io/mixpanel-flutter/mixpanel_flutter/Mixpanel/setLoggingEnabled.html)), if there is any error from Mixpanel, you should be able to see it. Could you paste any useful logs or the call stack when it crashes? Thanks!

It might be also worth trying to add Mixpanel to the flutter sample app(`flutter create my_app`) and if it works then compares the difference. We also have a demo app under our GitHub repo example folder.  https://github.com/mixpanel/mixpanel-flutter/tree/main/example.

**Comment by killhead** [comment] 2021-04-18 03:41
@zihejia Thank you for useful information. Didn't see much new via setLogginEnabled, but found issue when running with XCode and release mode.
The problem was that I used mixpanel.timeEvent/mixpanel.timeTrack in state build. It was somehow called on null. There is 'await' in initState so it's supposed that mixpanel is fulling initialized by the time of call inside build.

Here is minimalistic app code with failing lines commented:
```
class _MyAppAppState extends State<MyAppApp> {

  @override
  void initState() {
    super.initState();
    initMixpanel();
  }

  Future<void> initMixpanel() async {
    mixpanel = await Mixpanel.init("project_token",
        optOutTrackingDefault: false);
    mixpanel.setLoggingEnabled(true);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp',
      home: BlocBuilder<ProfileBloc, ProfileState>(
        builder: (context, state) {
          if (state is ProfileInitial) {
            // mixpanel.timeEvent("MyApp startup");    <<--- called on null
            return SplashPage();
          }
          if (state is ProfileFirsttime) {
            return OnboardingScreen();
          }
          // mixpanel.track("MyApp startup");    <<--- called on null
          mixpanel.identify((state as ProfileExist).profile.uid);
          return MainScreen(authorMode: widget.authorMode);
        },
      ),
    );
  }
}

```

**Comment by zihejia** [comment] 2021-04-21 02:13
hi @killhead , sorry for the late response. It looks like `mixpanel` has not finished initializing(async call) before you make the track call.  So if you need to call `track` in `build`, I'd suggest initializing `mixpanel` in there. Like below, you can even make a Mixpanel singleton to make it accessible across your app so you only need to call the `init()` once.

```
           @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp',
      home: BlocBuilder<ProfileBloc, ProfileState>(
        builder: (context, state) {
         if (_mixpanel == null) {
               _mixpanel = await Mixpanel.init("Your project token",
                  optOutTrackingDefault: false);
              _mixpanel.setLoggingEnabled(true);
            }
          if (state is ProfileInitial) {
            _mixpanel.timeEvent("MyApp startup");    
            return SplashPage();
          }
          if (state is ProfileFirsttime) {
            return OnboardingScreen();
          }
          _mixpanel.track("MyApp startup");    <<--- called on null
          mixpanel.identify((state as ProfileExist).profile.uid);
          return MainScreen(authorMode: widget.authorMode);
        },
      ),
    );
  }
}

```

**Comment by killhead** [comment] 2021-04-21 03:00
>  Like below, you can even make a Mixpanel singleton(see attached) to make it accessible across your app so you only need to call the `init()` once.

hi @zihejia,

Yes, done that already. Seems that tracking time of a App launch via MyApp.dart is not good idea as mixpanel is not ready yet.  For the rest, singleton is best way to go.

Thank you for your support!

**Comment by zihejia** [comment] 2021-04-21 17:41
Thanks @killhead. I'll close this however in case there are any issues please feel free to reopen.

**Closed by zihejia** 2021-04-21 17:41 UTC
